edition = "2018"
max_width = 80

comment_width = 80
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
format_code_in_doc_comments = true

imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"

blank_lines_upper_bound = 1
struct_lit_single_line = false
use_field_init_shorthand = true
condense_wildcard_suffixes = true
format_strings = false
reorder_impl_items = true
use_small_heuristics = "Max"
